-- ----------------------------------------------------------------------------
-- MySQL Workbench Migration
-- Migrated Schemata: information_schema, devschema
-- Source Schemata: information_schema, devschema
-- Created: Fri Jun 27 20:13:24 2014
-- ----------------------------------------------------------------------------

SET FOREIGN_KEY_CHECKS = 0;;

-- ----------------------------------------------------------------------------
-- Schema information_schema
-- ----------------------------------------------------------------------------
DROP SCHEMA IF EXISTS `information_schema` ;
CREATE SCHEMA IF NOT EXISTS `information_schema` ;

-- ----------------------------------------------------------------------------
-- Table information_schema.CHARACTER_SETS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`CHARACTER_SETS` (
  `CHARACTER_SET_NAME` VARCHAR(32) NOT NULL DEFAULT '',
  `DEFAULT_COLLATE_NAME` VARCHAR(32) NOT NULL DEFAULT '',
  `DESCRIPTION` VARCHAR(60) NOT NULL DEFAULT '',
  `MAXLEN` BIGINT(3) NOT NULL DEFAULT '0')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.CLIENT_STATISTICS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`CLIENT_STATISTICS` (
  `CLIENT` VARCHAR(64) NOT NULL DEFAULT '',
  `TOTAL_CONNECTIONS` INT(21) NOT NULL DEFAULT '0',
  `CONCURRENT_CONNECTIONS` INT(21) NOT NULL DEFAULT '0',
  `CONNECTED_TIME` INT(21) NOT NULL DEFAULT '0',
  `BUSY_TIME` INT(21) NOT NULL DEFAULT '0',
  `CPU_TIME` INT(21) NOT NULL DEFAULT '0',
  `BYTES_RECEIVED` INT(21) NOT NULL DEFAULT '0',
  `BYTES_SENT` INT(21) NOT NULL DEFAULT '0',
  `BINLOG_BYTES_WRITTEN` INT(21) NOT NULL DEFAULT '0',
  `ROWS_FETCHED` INT(21) NOT NULL DEFAULT '0',
  `ROWS_UPDATED` INT(21) NOT NULL DEFAULT '0',
  `TABLE_ROWS_READ` INT(21) NOT NULL DEFAULT '0',
  `SELECT_COMMANDS` INT(21) NOT NULL DEFAULT '0',
  `UPDATE_COMMANDS` INT(21) NOT NULL DEFAULT '0',
  `OTHER_COMMANDS` INT(21) NOT NULL DEFAULT '0',
  `COMMIT_TRANSACTIONS` INT(21) NOT NULL DEFAULT '0',
  `ROLLBACK_TRANSACTIONS` INT(21) NOT NULL DEFAULT '0',
  `DENIED_CONNECTIONS` INT(21) NOT NULL DEFAULT '0',
  `LOST_CONNECTIONS` INT(21) NOT NULL DEFAULT '0',
  `ACCESS_DENIED` INT(21) NOT NULL DEFAULT '0',
  `EMPTY_QUERIES` INT(21) NOT NULL DEFAULT '0')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.COLLATIONS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`COLLATIONS` (
  `COLLATION_NAME` VARCHAR(32) NOT NULL DEFAULT '',
  `CHARACTER_SET_NAME` VARCHAR(32) NOT NULL DEFAULT '',
  `ID` BIGINT(11) NOT NULL DEFAULT '0',
  `IS_DEFAULT` VARCHAR(3) NOT NULL DEFAULT '',
  `IS_COMPILED` VARCHAR(3) NOT NULL DEFAULT '',
  `SORTLEN` BIGINT(3) NOT NULL DEFAULT '0')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.COLLATION_CHARACTER_SET_APPLICABILITY
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`COLLATION_CHARACTER_SET_APPLICABILITY` (
  `COLLATION_NAME` VARCHAR(32) NOT NULL DEFAULT '',
  `CHARACTER_SET_NAME` VARCHAR(32) NOT NULL DEFAULT '')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.COLUMNS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`COLUMNS` (
  `TABLE_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `COLUMN_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `ORDINAL_POSITION` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `COLUMN_DEFAULT` LONGTEXT NULL DEFAULT NULL,
  `IS_NULLABLE` VARCHAR(3) NOT NULL DEFAULT '',
  `DATA_TYPE` VARCHAR(64) NOT NULL DEFAULT '',
  `CHARACTER_MAXIMUM_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `CHARACTER_OCTET_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `NUMERIC_PRECISION` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `NUMERIC_SCALE` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `CHARACTER_SET_NAME` VARCHAR(32) NULL DEFAULT NULL,
  `COLLATION_NAME` VARCHAR(32) NULL DEFAULT NULL,
  `COLUMN_TYPE` LONGTEXT NOT NULL,
  `COLUMN_KEY` VARCHAR(3) NOT NULL DEFAULT '',
  `EXTRA` VARCHAR(27) NOT NULL DEFAULT '',
  `PRIVILEGES` VARCHAR(80) NOT NULL DEFAULT '',
  `COLUMN_COMMENT` VARCHAR(1024) NOT NULL DEFAULT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.COLUMN_PRIVILEGES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`COLUMN_PRIVILEGES` (
  `GRANTEE` VARCHAR(81) NOT NULL DEFAULT '',
  `TABLE_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `COLUMN_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `PRIVILEGE_TYPE` VARCHAR(64) NOT NULL DEFAULT '',
  `IS_GRANTABLE` VARCHAR(3) NOT NULL DEFAULT '')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.INDEX_STATISTICS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`INDEX_STATISTICS` (
  `TABLE_SCHEMA` VARCHAR(192) NOT NULL DEFAULT '',
  `TABLE_NAME` VARCHAR(192) NOT NULL DEFAULT '',
  `INDEX_NAME` VARCHAR(192) NOT NULL DEFAULT '',
  `ROWS_READ` INT(21) NOT NULL DEFAULT '0')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.ENGINES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`ENGINES` (
  `ENGINE` VARCHAR(64) NOT NULL DEFAULT '',
  `SUPPORT` VARCHAR(8) NOT NULL DEFAULT '',
  `COMMENT` VARCHAR(80) NOT NULL DEFAULT '',
  `TRANSACTIONS` VARCHAR(3) NULL DEFAULT NULL,
  `XA` VARCHAR(3) NULL DEFAULT NULL,
  `SAVEPOINTS` VARCHAR(3) NULL DEFAULT NULL)
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.EVENTS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`EVENTS` (
  `EVENT_CATALOG` VARCHAR(64) NOT NULL DEFAULT '',
  `EVENT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `EVENT_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `DEFINER` VARCHAR(77) NOT NULL DEFAULT '',
  `TIME_ZONE` VARCHAR(64) NOT NULL DEFAULT '',
  `EVENT_BODY` VARCHAR(8) NOT NULL DEFAULT '',
  `EVENT_DEFINITION` LONGTEXT NOT NULL,
  `EVENT_TYPE` VARCHAR(9) NOT NULL DEFAULT '',
  `EXECUTE_AT` DATETIME NULL DEFAULT NULL,
  `INTERVAL_VALUE` VARCHAR(256) NULL DEFAULT NULL,
  `INTERVAL_FIELD` VARCHAR(18) NULL DEFAULT NULL,
  `SQL_MODE` VARCHAR(8192) NOT NULL DEFAULT '',
  `STARTS` DATETIME NULL DEFAULT NULL,
  `ENDS` DATETIME NULL DEFAULT NULL,
  `STATUS` VARCHAR(18) NOT NULL DEFAULT '',
  `ON_COMPLETION` VARCHAR(12) NOT NULL DEFAULT '',
  `CREATED` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_ALTERED` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_EXECUTED` DATETIME NULL DEFAULT NULL,
  `EVENT_COMMENT` VARCHAR(64) NOT NULL DEFAULT '',
  `ORIGINATOR` BIGINT(10) NOT NULL DEFAULT '0',
  `CHARACTER_SET_CLIENT` VARCHAR(32) NOT NULL DEFAULT '',
  `COLLATION_CONNECTION` VARCHAR(32) NOT NULL DEFAULT '',
  `DATABASE_COLLATION` VARCHAR(32) NOT NULL DEFAULT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.FILES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`FILES` (
  `FILE_ID` BIGINT(4) NOT NULL DEFAULT '0',
  `FILE_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `FILE_TYPE` VARCHAR(20) NOT NULL DEFAULT '',
  `TABLESPACE_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `TABLE_CATALOG` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLE_SCHEMA` VARCHAR(64) NULL DEFAULT NULL,
  `TABLE_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `LOGFILE_GROUP_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `LOGFILE_GROUP_NUMBER` BIGINT(4) NULL DEFAULT NULL,
  `ENGINE` VARCHAR(64) NOT NULL DEFAULT '',
  `FULLTEXT_KEYS` VARCHAR(64) NULL DEFAULT NULL,
  `DELETED_ROWS` BIGINT(4) NULL DEFAULT NULL,
  `UPDATE_COUNT` BIGINT(4) NULL DEFAULT NULL,
  `FREE_EXTENTS` BIGINT(4) NULL DEFAULT NULL,
  `TOTAL_EXTENTS` BIGINT(4) NULL DEFAULT NULL,
  `EXTENT_SIZE` BIGINT(4) NOT NULL DEFAULT '0',
  `INITIAL_SIZE` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `MAXIMUM_SIZE` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `AUTOEXTEND_SIZE` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `CREATION_TIME` DATETIME NULL DEFAULT NULL,
  `LAST_UPDATE_TIME` DATETIME NULL DEFAULT NULL,
  `LAST_ACCESS_TIME` DATETIME NULL DEFAULT NULL,
  `RECOVER_TIME` BIGINT(4) NULL DEFAULT NULL,
  `TRANSACTION_COUNTER` BIGINT(4) NULL DEFAULT NULL,
  `VERSION` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `ROW_FORMAT` VARCHAR(10) NULL DEFAULT NULL,
  `TABLE_ROWS` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `AVG_ROW_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `MAX_DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `INDEX_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `DATA_FREE` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `CREATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_TIME` DATETIME NULL DEFAULT NULL,
  `CHECK_TIME` DATETIME NULL DEFAULT NULL,
  `CHECKSUM` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `STATUS` VARCHAR(20) NOT NULL DEFAULT '',
  `EXTRA` VARCHAR(255) NULL DEFAULT NULL)
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.GLOBAL_STATUS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`GLOBAL_STATUS` (
  `VARIABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `VARIABLE_VALUE` VARCHAR(1024) NULL DEFAULT NULL)
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.GLOBAL_VARIABLES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`GLOBAL_VARIABLES` (
  `VARIABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `VARIABLE_VALUE` VARCHAR(1024) NULL DEFAULT NULL)
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.KEY_COLUMN_USAGE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`KEY_COLUMN_USAGE` (
  `CONSTRAINT_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `CONSTRAINT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `CONSTRAINT_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLE_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `COLUMN_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `ORDINAL_POSITION` BIGINT(10) NOT NULL DEFAULT '0',
  `POSITION_IN_UNIQUE_CONSTRAINT` BIGINT(10) NULL DEFAULT NULL,
  `REFERENCED_TABLE_SCHEMA` VARCHAR(64) NULL DEFAULT NULL,
  `REFERENCED_TABLE_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `REFERENCED_COLUMN_NAME` VARCHAR(64) NULL DEFAULT NULL)
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.PARAMETERS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`PARAMETERS` (
  `SPECIFIC_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `SPECIFIC_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `SPECIFIC_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `ORDINAL_POSITION` INT(21) NOT NULL DEFAULT '0',
  `PARAMETER_MODE` VARCHAR(5) NULL DEFAULT NULL,
  `PARAMETER_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `DATA_TYPE` VARCHAR(64) NOT NULL DEFAULT '',
  `CHARACTER_MAXIMUM_LENGTH` INT(21) NULL DEFAULT NULL,
  `CHARACTER_OCTET_LENGTH` INT(21) NULL DEFAULT NULL,
  `NUMERIC_PRECISION` INT(21) NULL DEFAULT NULL,
  `NUMERIC_SCALE` INT(21) NULL DEFAULT NULL,
  `CHARACTER_SET_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `COLLATION_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `DTD_IDENTIFIER` LONGTEXT NOT NULL,
  `ROUTINE_TYPE` VARCHAR(9) NOT NULL DEFAULT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.PARTITIONS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`PARTITIONS` (
  `TABLE_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `PARTITION_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `SUBPARTITION_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `PARTITION_ORDINAL_POSITION` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `SUBPARTITION_ORDINAL_POSITION` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `PARTITION_METHOD` VARCHAR(18) NULL DEFAULT NULL,
  `SUBPARTITION_METHOD` VARCHAR(12) NULL DEFAULT NULL,
  `PARTITION_EXPRESSION` LONGTEXT NULL DEFAULT NULL,
  `SUBPARTITION_EXPRESSION` LONGTEXT NULL DEFAULT NULL,
  `PARTITION_DESCRIPTION` LONGTEXT NULL DEFAULT NULL,
  `TABLE_ROWS` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `AVG_ROW_LENGTH` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `DATA_LENGTH` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `MAX_DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `INDEX_LENGTH` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `DATA_FREE` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `CREATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_TIME` DATETIME NULL DEFAULT NULL,
  `CHECK_TIME` DATETIME NULL DEFAULT NULL,
  `CHECKSUM` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `PARTITION_COMMENT` VARCHAR(80) NOT NULL DEFAULT '',
  `NODEGROUP` VARCHAR(12) NOT NULL DEFAULT '',
  `TABLESPACE_NAME` VARCHAR(64) NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.PLUGINS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`PLUGINS` (
  `PLUGIN_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `PLUGIN_VERSION` VARCHAR(20) NOT NULL DEFAULT '',
  `PLUGIN_STATUS` VARCHAR(10) NOT NULL DEFAULT '',
  `PLUGIN_TYPE` VARCHAR(80) NOT NULL DEFAULT '',
  `PLUGIN_TYPE_VERSION` VARCHAR(20) NOT NULL DEFAULT '',
  `PLUGIN_LIBRARY` VARCHAR(64) NULL DEFAULT NULL,
  `PLUGIN_LIBRARY_VERSION` VARCHAR(20) NULL DEFAULT NULL,
  `PLUGIN_AUTHOR` VARCHAR(64) NULL DEFAULT NULL,
  `PLUGIN_DESCRIPTION` LONGTEXT NULL DEFAULT NULL,
  `PLUGIN_LICENSE` VARCHAR(80) NULL DEFAULT NULL,
  `LOAD_OPTION` VARCHAR(64) NOT NULL DEFAULT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.PROCESSLIST
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`PROCESSLIST` (
  `ID` BIGINT(4) NOT NULL DEFAULT '0',
  `USER` VARCHAR(16) NOT NULL DEFAULT '',
  `HOST` VARCHAR(64) NOT NULL DEFAULT '',
  `DB` VARCHAR(64) NULL DEFAULT NULL,
  `COMMAND` VARCHAR(16) NOT NULL DEFAULT '',
  `TIME` INT(7) NOT NULL DEFAULT '0',
  `STATE` VARCHAR(64) NULL DEFAULT NULL,
  `INFO` LONGTEXT NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.PROFILING
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`PROFILING` (
  `QUERY_ID` INT(20) NOT NULL DEFAULT '0',
  `SEQ` INT(20) NOT NULL DEFAULT '0',
  `STATE` VARCHAR(30) NOT NULL DEFAULT '',
  `DURATION` DECIMAL(9,6) NOT NULL DEFAULT '0.000000',
  `CPU_USER` DECIMAL(9,6) NULL DEFAULT NULL,
  `CPU_SYSTEM` DECIMAL(9,6) NULL DEFAULT NULL,
  `CONTEXT_VOLUNTARY` INT(20) NULL DEFAULT NULL,
  `CONTEXT_INVOLUNTARY` INT(20) NULL DEFAULT NULL,
  `BLOCK_OPS_IN` INT(20) NULL DEFAULT NULL,
  `BLOCK_OPS_OUT` INT(20) NULL DEFAULT NULL,
  `MESSAGES_SENT` INT(20) NULL DEFAULT NULL,
  `MESSAGES_RECEIVED` INT(20) NULL DEFAULT NULL,
  `PAGE_FAULTS_MAJOR` INT(20) NULL DEFAULT NULL,
  `PAGE_FAULTS_MINOR` INT(20) NULL DEFAULT NULL,
  `SWAPS` INT(20) NULL DEFAULT NULL,
  `SOURCE_FUNCTION` VARCHAR(30) NULL DEFAULT NULL,
  `SOURCE_FILE` VARCHAR(20) NULL DEFAULT NULL,
  `SOURCE_LINE` INT(20) NULL DEFAULT NULL)
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.REFERENTIAL_CONSTRAINTS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`REFERENTIAL_CONSTRAINTS` (
  `CONSTRAINT_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `CONSTRAINT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `CONSTRAINT_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `UNIQUE_CONSTRAINT_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `UNIQUE_CONSTRAINT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `UNIQUE_CONSTRAINT_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `MATCH_OPTION` VARCHAR(64) NOT NULL DEFAULT '',
  `UPDATE_RULE` VARCHAR(64) NOT NULL DEFAULT '',
  `DELETE_RULE` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `REFERENCED_TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.ROUTINES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`ROUTINES` (
  `SPECIFIC_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `ROUTINE_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `ROUTINE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `ROUTINE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `ROUTINE_TYPE` VARCHAR(9) NOT NULL DEFAULT '',
  `DATA_TYPE` VARCHAR(64) NOT NULL DEFAULT '',
  `CHARACTER_MAXIMUM_LENGTH` INT(21) NULL DEFAULT NULL,
  `CHARACTER_OCTET_LENGTH` INT(21) NULL DEFAULT NULL,
  `NUMERIC_PRECISION` INT(21) NULL DEFAULT NULL,
  `NUMERIC_SCALE` INT(21) NULL DEFAULT NULL,
  `CHARACTER_SET_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `COLLATION_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `DTD_IDENTIFIER` LONGTEXT NULL DEFAULT NULL,
  `ROUTINE_BODY` VARCHAR(8) NOT NULL DEFAULT '',
  `ROUTINE_DEFINITION` LONGTEXT NULL DEFAULT NULL,
  `EXTERNAL_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `EXTERNAL_LANGUAGE` VARCHAR(64) NULL DEFAULT NULL,
  `PARAMETER_STYLE` VARCHAR(8) NOT NULL DEFAULT '',
  `IS_DETERMINISTIC` VARCHAR(3) NOT NULL DEFAULT '',
  `SQL_DATA_ACCESS` VARCHAR(64) NOT NULL DEFAULT '',
  `SQL_PATH` VARCHAR(64) NULL DEFAULT NULL,
  `SECURITY_TYPE` VARCHAR(7) NOT NULL DEFAULT '',
  `CREATED` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_ALTERED` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `SQL_MODE` VARCHAR(8192) NOT NULL DEFAULT '',
  `ROUTINE_COMMENT` LONGTEXT NOT NULL,
  `DEFINER` VARCHAR(77) NOT NULL DEFAULT '',
  `CHARACTER_SET_CLIENT` VARCHAR(32) NOT NULL DEFAULT '',
  `COLLATION_CONNECTION` VARCHAR(32) NOT NULL DEFAULT '',
  `DATABASE_COLLATION` VARCHAR(32) NOT NULL DEFAULT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.SCHEMATA
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`SCHEMATA` (
  `CATALOG_NAME` VARCHAR(512) NOT NULL DEFAULT '',
  `SCHEMA_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `DEFAULT_CHARACTER_SET_NAME` VARCHAR(32) NOT NULL DEFAULT '',
  `DEFAULT_COLLATION_NAME` VARCHAR(32) NOT NULL DEFAULT '',
  `SQL_PATH` VARCHAR(512) NULL DEFAULT NULL)
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.SCHEMA_PRIVILEGES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`SCHEMA_PRIVILEGES` (
  `GRANTEE` VARCHAR(81) NOT NULL DEFAULT '',
  `TABLE_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `PRIVILEGE_TYPE` VARCHAR(64) NOT NULL DEFAULT '',
  `IS_GRANTABLE` VARCHAR(3) NOT NULL DEFAULT '')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.SESSION_STATUS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`SESSION_STATUS` (
  `VARIABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `VARIABLE_VALUE` VARCHAR(1024) NULL DEFAULT NULL)
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.SESSION_VARIABLES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`SESSION_VARIABLES` (
  `VARIABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `VARIABLE_VALUE` VARCHAR(1024) NULL DEFAULT NULL)
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.STATISTICS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`STATISTICS` (
  `TABLE_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `NON_UNIQUE` BIGINT(1) NOT NULL DEFAULT '0',
  `INDEX_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `INDEX_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `SEQ_IN_INDEX` BIGINT(2) NOT NULL DEFAULT '0',
  `COLUMN_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `COLLATION` VARCHAR(1) NULL DEFAULT NULL,
  `CARDINALITY` BIGINT(21) NULL DEFAULT NULL,
  `SUB_PART` BIGINT(3) NULL DEFAULT NULL,
  `PACKED` VARCHAR(10) NULL DEFAULT NULL,
  `NULLABLE` VARCHAR(3) NOT NULL DEFAULT '',
  `INDEX_TYPE` VARCHAR(16) NOT NULL DEFAULT '',
  `COMMENT` VARCHAR(16) NULL DEFAULT NULL,
  `INDEX_COMMENT` VARCHAR(1024) NOT NULL DEFAULT '')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.TABLES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`TABLES` (
  `TABLE_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLE_TYPE` VARCHAR(64) NOT NULL DEFAULT '',
  `ENGINE` VARCHAR(64) NULL DEFAULT NULL,
  `VERSION` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `ROW_FORMAT` VARCHAR(10) NULL DEFAULT NULL,
  `TABLE_ROWS` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `AVG_ROW_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `MAX_DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `INDEX_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `DATA_FREE` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `AUTO_INCREMENT` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `CREATE_TIME` DATETIME NULL DEFAULT NULL,
  `UPDATE_TIME` DATETIME NULL DEFAULT NULL,
  `CHECK_TIME` DATETIME NULL DEFAULT NULL,
  `TABLE_COLLATION` VARCHAR(32) NULL DEFAULT NULL,
  `CHECKSUM` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `CREATE_OPTIONS` VARCHAR(255) NULL DEFAULT NULL,
  `TABLE_COMMENT` VARCHAR(2048) NOT NULL DEFAULT '')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.TABLESPACES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`TABLESPACES` (
  `TABLESPACE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `ENGINE` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLESPACE_TYPE` VARCHAR(64) NULL DEFAULT NULL,
  `LOGFILE_GROUP_NAME` VARCHAR(64) NULL DEFAULT NULL,
  `EXTENT_SIZE` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `AUTOEXTEND_SIZE` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `MAXIMUM_SIZE` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `NODEGROUP_ID` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `TABLESPACE_COMMENT` VARCHAR(2048) NULL DEFAULT NULL)
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.TABLE_CONSTRAINTS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`TABLE_CONSTRAINTS` (
  `CONSTRAINT_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `CONSTRAINT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `CONSTRAINT_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `CONSTRAINT_TYPE` VARCHAR(64) NOT NULL DEFAULT '')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.TABLE_PRIVILEGES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`TABLE_PRIVILEGES` (
  `GRANTEE` VARCHAR(81) NOT NULL DEFAULT '',
  `TABLE_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `PRIVILEGE_TYPE` VARCHAR(64) NOT NULL DEFAULT '',
  `IS_GRANTABLE` VARCHAR(3) NOT NULL DEFAULT '')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.TABLE_STATISTICS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`TABLE_STATISTICS` (
  `TABLE_SCHEMA` VARCHAR(192) NOT NULL DEFAULT '',
  `TABLE_NAME` VARCHAR(192) NOT NULL DEFAULT '',
  `ROWS_READ` INT(21) NOT NULL DEFAULT '0',
  `ROWS_CHANGED` INT(21) NOT NULL DEFAULT '0',
  `ROWS_CHANGED_X_INDEXES` INT(21) NOT NULL DEFAULT '0')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.THREAD_STATISTICS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`THREAD_STATISTICS` (
  `THREAD_ID` INT(21) NOT NULL DEFAULT '0',
  `TOTAL_CONNECTIONS` INT(21) NOT NULL DEFAULT '0',
  `CONCURRENT_CONNECTIONS` INT(21) NOT NULL DEFAULT '0',
  `CONNECTED_TIME` INT(21) NOT NULL DEFAULT '0',
  `BUSY_TIME` INT(21) NOT NULL DEFAULT '0',
  `CPU_TIME` INT(21) NOT NULL DEFAULT '0',
  `BYTES_RECEIVED` INT(21) NOT NULL DEFAULT '0',
  `BYTES_SENT` INT(21) NOT NULL DEFAULT '0',
  `BINLOG_BYTES_WRITTEN` INT(21) NOT NULL DEFAULT '0',
  `ROWS_FETCHED` INT(21) NOT NULL DEFAULT '0',
  `ROWS_UPDATED` INT(21) NOT NULL DEFAULT '0',
  `TABLE_ROWS_READ` INT(21) NOT NULL DEFAULT '0',
  `SELECT_COMMANDS` INT(21) NOT NULL DEFAULT '0',
  `UPDATE_COMMANDS` INT(21) NOT NULL DEFAULT '0',
  `OTHER_COMMANDS` INT(21) NOT NULL DEFAULT '0',
  `COMMIT_TRANSACTIONS` INT(21) NOT NULL DEFAULT '0',
  `ROLLBACK_TRANSACTIONS` INT(21) NOT NULL DEFAULT '0',
  `DENIED_CONNECTIONS` INT(21) NOT NULL DEFAULT '0',
  `LOST_CONNECTIONS` INT(21) NOT NULL DEFAULT '0',
  `ACCESS_DENIED` INT(21) NOT NULL DEFAULT '0',
  `EMPTY_QUERIES` INT(21) NOT NULL DEFAULT '0')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.TRIGGERS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`TRIGGERS` (
  `TRIGGER_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `TRIGGER_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `TRIGGER_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `EVENT_MANIPULATION` VARCHAR(6) NOT NULL DEFAULT '',
  `EVENT_OBJECT_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `EVENT_OBJECT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `EVENT_OBJECT_TABLE` VARCHAR(64) NOT NULL DEFAULT '',
  `ACTION_ORDER` BIGINT(4) NOT NULL DEFAULT '0',
  `ACTION_CONDITION` LONGTEXT NULL DEFAULT NULL,
  `ACTION_STATEMENT` LONGTEXT NOT NULL,
  `ACTION_ORIENTATION` VARCHAR(9) NOT NULL DEFAULT '',
  `ACTION_TIMING` VARCHAR(6) NOT NULL DEFAULT '',
  `ACTION_REFERENCE_OLD_TABLE` VARCHAR(64) NULL DEFAULT NULL,
  `ACTION_REFERENCE_NEW_TABLE` VARCHAR(64) NULL DEFAULT NULL,
  `ACTION_REFERENCE_OLD_ROW` VARCHAR(3) NOT NULL DEFAULT '',
  `ACTION_REFERENCE_NEW_ROW` VARCHAR(3) NOT NULL DEFAULT '',
  `CREATED` DATETIME NULL DEFAULT NULL,
  `SQL_MODE` VARCHAR(8192) NOT NULL DEFAULT '',
  `DEFINER` VARCHAR(77) NOT NULL DEFAULT '',
  `CHARACTER_SET_CLIENT` VARCHAR(32) NOT NULL DEFAULT '',
  `COLLATION_CONNECTION` VARCHAR(32) NOT NULL DEFAULT '',
  `DATABASE_COLLATION` VARCHAR(32) NOT NULL DEFAULT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.USER_PRIVILEGES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`USER_PRIVILEGES` (
  `GRANTEE` VARCHAR(81) NOT NULL DEFAULT '',
  `TABLE_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `PRIVILEGE_TYPE` VARCHAR(64) NOT NULL DEFAULT '',
  `IS_GRANTABLE` VARCHAR(3) NOT NULL DEFAULT '')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.USER_STATISTICS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`USER_STATISTICS` (
  `USER` VARCHAR(48) NOT NULL DEFAULT '',
  `TOTAL_CONNECTIONS` INT(21) NOT NULL DEFAULT '0',
  `CONCURRENT_CONNECTIONS` INT(21) NOT NULL DEFAULT '0',
  `CONNECTED_TIME` INT(21) NOT NULL DEFAULT '0',
  `BUSY_TIME` INT(21) NOT NULL DEFAULT '0',
  `CPU_TIME` INT(21) NOT NULL DEFAULT '0',
  `BYTES_RECEIVED` INT(21) NOT NULL DEFAULT '0',
  `BYTES_SENT` INT(21) NOT NULL DEFAULT '0',
  `BINLOG_BYTES_WRITTEN` INT(21) NOT NULL DEFAULT '0',
  `ROWS_FETCHED` INT(21) NOT NULL DEFAULT '0',
  `ROWS_UPDATED` INT(21) NOT NULL DEFAULT '0',
  `TABLE_ROWS_READ` INT(21) NOT NULL DEFAULT '0',
  `SELECT_COMMANDS` INT(21) NOT NULL DEFAULT '0',
  `UPDATE_COMMANDS` INT(21) NOT NULL DEFAULT '0',
  `OTHER_COMMANDS` INT(21) NOT NULL DEFAULT '0',
  `COMMIT_TRANSACTIONS` INT(21) NOT NULL DEFAULT '0',
  `ROLLBACK_TRANSACTIONS` INT(21) NOT NULL DEFAULT '0',
  `DENIED_CONNECTIONS` INT(21) NOT NULL DEFAULT '0',
  `LOST_CONNECTIONS` INT(21) NOT NULL DEFAULT '0',
  `ACCESS_DENIED` INT(21) NOT NULL DEFAULT '0',
  `EMPTY_QUERIES` INT(21) NOT NULL DEFAULT '0')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.VIEWS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`VIEWS` (
  `TABLE_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `VIEW_DEFINITION` LONGTEXT NOT NULL,
  `CHECK_OPTION` VARCHAR(8) NOT NULL DEFAULT '',
  `IS_UPDATABLE` VARCHAR(3) NOT NULL DEFAULT '',
  `DEFINER` VARCHAR(77) NOT NULL DEFAULT '',
  `SECURITY_TYPE` VARCHAR(7) NOT NULL DEFAULT '',
  `CHARACTER_SET_CLIENT` VARCHAR(32) NOT NULL DEFAULT '',
  `COLLATION_CONNECTION` VARCHAR(32) NOT NULL DEFAULT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.INNODB_BUFFER_PAGE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`INNODB_BUFFER_PAGE` (
  `POOL_ID` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `BLOCK_ID` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `SPACE` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `PAGE_NUMBER` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `PAGE_TYPE` VARCHAR(64) NULL DEFAULT NULL,
  `FLUSH_TYPE` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `FIX_COUNT` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `IS_HASHED` VARCHAR(3) NULL DEFAULT NULL,
  `NEWEST_MODIFICATION` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `OLDEST_MODIFICATION` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `ACCESS_TIME` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `TABLE_NAME` VARCHAR(1024) NULL DEFAULT NULL,
  `INDEX_NAME` VARCHAR(1024) NULL DEFAULT NULL,
  `NUMBER_RECORDS` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `DATA_SIZE` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `COMPRESSED_SIZE` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `PAGE_STATE` VARCHAR(64) NULL DEFAULT NULL,
  `IO_FIX` VARCHAR(64) NULL DEFAULT NULL,
  `IS_OLD` VARCHAR(3) NULL DEFAULT NULL,
  `FREE_PAGE_CLOCK` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.INNODB_TRX
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`INNODB_TRX` (
  `trx_id` VARCHAR(18) NOT NULL DEFAULT '',
  `trx_state` VARCHAR(13) NOT NULL DEFAULT '',
  `trx_started` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `trx_requested_lock_id` VARCHAR(81) NULL DEFAULT NULL,
  `trx_wait_started` DATETIME NULL DEFAULT NULL,
  `trx_weight` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `trx_mysql_thread_id` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `trx_query` VARCHAR(1024) NULL DEFAULT NULL,
  `trx_operation_state` VARCHAR(64) NULL DEFAULT NULL,
  `trx_tables_in_use` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `trx_tables_locked` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `trx_lock_structs` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `trx_lock_memory_bytes` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `trx_rows_locked` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `trx_rows_modified` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `trx_concurrency_tickets` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `trx_isolation_level` VARCHAR(16) NOT NULL DEFAULT '',
  `trx_unique_checks` INT(1) NOT NULL DEFAULT '0',
  `trx_foreign_key_checks` INT(1) NOT NULL DEFAULT '0',
  `trx_last_foreign_key_error` VARCHAR(256) NULL DEFAULT NULL,
  `trx_adaptive_hash_latched` INT(1) NOT NULL DEFAULT '0',
  `trx_adaptive_hash_timeout` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.INNODB_BUFFER_POOL_STATS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`INNODB_BUFFER_POOL_STATS` (
  `POOL_ID` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `POOL_SIZE` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `FREE_BUFFERS` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `DATABASE_PAGES` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `OLD_DATABASE_PAGES` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `MODIFIED_DATABASE_PAGES` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `PENDING_DECOMPRESS` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `PENDING_READS` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `PENDING_FLUSH_LRU` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `PENDING_FLUSH_LIST` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `PAGES_MADE_YOUNG` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `PAGES_NOT_MADE_YOUNG` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `PAGES_MADE_YOUNG_RATE` DOUBLE NOT NULL DEFAULT '0',
  `PAGES_MADE_NOT_YOUNG_RATE` DOUBLE NOT NULL DEFAULT '0',
  `NUMBER_PAGES_READ` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `NUMBER_PAGES_CREATED` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `NUMBER_PAGES_WRITTEN` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `PAGES_READ_RATE` DOUBLE NOT NULL DEFAULT '0',
  `PAGES_CREATE_RATE` DOUBLE NOT NULL DEFAULT '0',
  `PAGES_WRITTEN_RATE` DOUBLE NOT NULL DEFAULT '0',
  `NUMBER_PAGES_GET` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `HIT_RATE` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `YOUNG_MAKE_PER_THOUSAND_GETS` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `NOT_YOUNG_MAKE_PER_THOUSAND_GETS` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `NUMBER_PAGES_READ_AHEAD` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `NUMBER_READ_AHEAD_EVICTED` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `READ_AHEAD_RATE` DOUBLE NOT NULL DEFAULT '0',
  `READ_AHEAD_EVICTED_RATE` DOUBLE NOT NULL DEFAULT '0',
  `LRU_IO_TOTAL` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `LRU_IO_CURRENT` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `UNCOMPRESS_TOTAL` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `UNCOMPRESS_CURRENT` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.INNODB_LOCK_WAITS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`INNODB_LOCK_WAITS` (
  `requesting_trx_id` VARCHAR(18) NOT NULL DEFAULT '',
  `requested_lock_id` VARCHAR(81) NOT NULL DEFAULT '',
  `blocking_trx_id` VARCHAR(18) NOT NULL DEFAULT '',
  `blocking_lock_id` VARCHAR(81) NOT NULL DEFAULT '')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.INNODB_CMPMEM
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`INNODB_CMPMEM` (
  `page_size` INT(5) NOT NULL DEFAULT '0',
  `buffer_pool_instance` INT(11) NOT NULL DEFAULT '0',
  `pages_used` INT(11) NOT NULL DEFAULT '0',
  `pages_free` INT(11) NOT NULL DEFAULT '0',
  `relocation_ops` BIGINT(21) NOT NULL DEFAULT '0',
  `relocation_time` INT(11) NOT NULL DEFAULT '0')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.INNODB_CMP
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`INNODB_CMP` (
  `page_size` INT(5) NOT NULL DEFAULT '0',
  `compress_ops` INT(11) NOT NULL DEFAULT '0',
  `compress_ops_ok` INT(11) NOT NULL DEFAULT '0',
  `compress_time` INT(11) NOT NULL DEFAULT '0',
  `uncompress_ops` INT(11) NOT NULL DEFAULT '0',
  `uncompress_time` INT(11) NOT NULL DEFAULT '0')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.INNODB_LOCKS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`INNODB_LOCKS` (
  `lock_id` VARCHAR(81) NOT NULL DEFAULT '',
  `lock_trx_id` VARCHAR(18) NOT NULL DEFAULT '',
  `lock_mode` VARCHAR(32) NOT NULL DEFAULT '',
  `lock_type` VARCHAR(32) NOT NULL DEFAULT '',
  `lock_table` VARCHAR(1024) NOT NULL DEFAULT '',
  `lock_index` VARCHAR(1024) NULL DEFAULT NULL,
  `lock_space` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `lock_page` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `lock_rec` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
  `lock_data` VARCHAR(8192) NULL DEFAULT NULL)
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.INNODB_CMPMEM_RESET
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`INNODB_CMPMEM_RESET` (
  `page_size` INT(5) NOT NULL DEFAULT '0',
  `buffer_pool_instance` INT(11) NOT NULL DEFAULT '0',
  `pages_used` INT(11) NOT NULL DEFAULT '0',
  `pages_free` INT(11) NOT NULL DEFAULT '0',
  `relocation_ops` BIGINT(21) NOT NULL DEFAULT '0',
  `relocation_time` INT(11) NOT NULL DEFAULT '0')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.INNODB_CMP_RESET
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`INNODB_CMP_RESET` (
  `page_size` INT(5) NOT NULL DEFAULT '0',
  `compress_ops` INT(11) NOT NULL DEFAULT '0',
  `compress_ops_ok` INT(11) NOT NULL DEFAULT '0',
  `compress_time` INT(11) NOT NULL DEFAULT '0',
  `uncompress_ops` INT(11) NOT NULL DEFAULT '0',
  `uncompress_time` INT(11) NOT NULL DEFAULT '0')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table information_schema.INNODB_BUFFER_PAGE_LRU
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `information_schema`.`INNODB_BUFFER_PAGE_LRU` (
  `POOL_ID` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `LRU_POSITION` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `SPACE` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `PAGE_NUMBER` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `PAGE_TYPE` VARCHAR(64) NULL DEFAULT NULL,
  `FLUSH_TYPE` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `FIX_COUNT` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `IS_HASHED` VARCHAR(3) NULL DEFAULT NULL,
  `NEWEST_MODIFICATION` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `OLDEST_MODIFICATION` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `ACCESS_TIME` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `TABLE_NAME` VARCHAR(1024) NULL DEFAULT NULL,
  `INDEX_NAME` VARCHAR(1024) NULL DEFAULT NULL,
  `NUMBER_RECORDS` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `DATA_SIZE` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `COMPRESSED_SIZE` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0',
  `COMPRESSED` VARCHAR(3) NULL DEFAULT NULL,
  `IO_FIX` VARCHAR(64) NULL DEFAULT NULL,
  `IS_OLD` VARCHAR(3) NULL DEFAULT NULL,
  `FREE_PAGE_CLOCK` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Schema devschema
-- ----------------------------------------------------------------------------
DROP SCHEMA IF EXISTS `devschema` ;
CREATE SCHEMA IF NOT EXISTS `devschema` ;

-- ----------------------------------------------------------------------------
-- Table devschema.category
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `devschema`.`category` (
  `cat_id` VARCHAR(50) NOT NULL DEFAULT '0',
  `label` VARCHAR(25) NOT NULL,
  `cat_order` INT(11) NOT NULL DEFAULT '0',
  `icon` VARCHAR(100) NULL DEFAULT NULL,
  `isvisible` VARCHAR(5) NULL DEFAULT 'true',
  `isdefault` VARCHAR(5) NOT NULL DEFAULT 'false',
  PRIMARY KEY (`cat_id`),
  UNIQUE INDEX `cat_id_UNIQUE` (`cat_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table devschema.members
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `devschema`.`members` (
  `mem_email_id` VARCHAR(255) NOT NULL,
  `mem_first_name` VARCHAR(25) NOT NULL,
  `mem_last_name` VARCHAR(25) NULL DEFAULT NULL,
  `mem_display_name` VARCHAR(50) NOT NULL,
  `mem_password` VARCHAR(71) NULL DEFAULT NULL,
  `mem_join_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `mem_timezone` TINYINT(4) NULL DEFAULT NULL,
  `mem_day_light_saving` VARCHAR(5) NULL DEFAULT NULL,
  `mem_type` VARCHAR(10) NULL DEFAULT NULL,
  `mem_group` TINYINT(4) NULL DEFAULT NULL,
  `mem_status` TINYINT(4) NULL DEFAULT NULL,
  `mem_suspended_until` DATETIME NULL DEFAULT NULL,
  `mem_status_reason` VARCHAR(300) NULL DEFAULT NULL,
  `mem_last_login` DATETIME NULL DEFAULT NULL,
  `mem_birthday` DATE NULL DEFAULT NULL,
  `mem_location` VARCHAR(255) NULL DEFAULT NULL,
  `mem_validated` VARCHAR(5) NULL DEFAULT 'false',
  `mem_validated_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`mem_email_id`),
  UNIQUE INDEX `mem_email_id_UNIQUE` (`mem_email_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- ----------------------------------------------------------------------------
-- Table devschema.processes
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `devschema`.`processes` (
  `proc_id` VARCHAR(50) NOT NULL DEFAULT '0',
  `cat_id` VARCHAR(50) NOT NULL,
  `label` VARCHAR(25) NOT NULL,
  `proc_order` INT(11) NOT NULL DEFAULT '0',
  `icon` VARCHAR(100) NOT NULL,
  `type` VARCHAR(15) NOT NULL COMMENT 'tileview, listview, operations',
  `type_id` VARCHAR(15) NOT NULL,
  `type_name` VARCHAR(50) NOT NULL,
  `isvisible` VARCHAR(5) NOT NULL DEFAULT 'true',
  `isdefault` VARCHAR(5) NOT NULL DEFAULT 'false',
  `url` INT(200) NOT NULL,
  PRIMARY KEY (`proc_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- ----------------------------------------------------------------------------
-- Trigger devschema.category_BINS
-- ----------------------------------------------------------------------------
DELIMITER $$
USE `devschema`$$
CREATE DEFINER=`cpses_rbCjgtMYbJ`@`localhost` TRIGGER `category_BINS`
  BEFORE INSERT ON `category`
  FOR EACH ROW
  SET new.cat_id = uuid();

-- ----------------------------------------------------------------------------
-- Trigger devschema.process_BINS
-- ----------------------------------------------------------------------------
DELIMITER $$
USE `devschema`$$
CREATE DEFINER=`cpses_rbAGEDOquW`@`localhost` TRIGGER `process_BINS`
BEFORE
INSERT ON `processes`
FOR EACH ROW
SET new.proc_id = uuid();
SET FOREIGN_KEY_CHECKS = 1;;
